# Generated by Django 2.2.2 on 2020-07-17 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=700, null=True)),
                ('category', models.CharField(choices=[('WORLD', 'world'), ('ENVIORNMENT', 'environment'), ('TECHNOLOGY', 'technology'), ('DESIGN', 'design'), ('CULTURE', 'culture'), ('BUSINESS', 'business'), ('POLITICS', 'politics'), ('OPINION', 'opinion'), ('SCIENCE', 'science'), ('HEALTH', 'health'), ('STYLE', 'style'), ('TRAVEL', 'travel')], default=('WORLD', 'world'), max_length=50)),
                ('slug', models.SlugField()),
                ('excrpt', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('month', models.CharField(max_length=3, null=True)),
                ('day', models.CharField(default=datetime.datetime(2020, 7, 17, 11, 29, 8, 971689, tzinfo=utc), max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
