# Generated by Django 2.2.2 on 2020-07-17 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200717_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 12, 38, 37, 882586, tzinfo=utc), max_length=3),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
